name: Build and deploy Next.js app to Azure Web App - TrekCanada

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'TrekCanada'
  AZURE_WEBAPP_PACKAGE_PATH: './release.zip'
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp -r .next public package.json package-lock.json next.config.js server.js node_modules deploy/
          cd deploy
          zip -r ../release.zip . -x '*.git*' -x '*.env.local*' -x '*node_modules/.cache*'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AAB5DDDEA88B474795A5EBB908C270A5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_238940C03ABC4D52A5EAE8B5AB1B2814 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_52BBFF95671A4BB6BD701CD97478C9BA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
